name: NES - v14

on:
  workflow_dispatch:
  
jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set a timeout of 15 minutes for this job
    environment: production
    steps:
    - uses: actions/checkout@v3
      with:
          ref: angular-v14-nes
    - name: Build the Docker image
      run: |
        docker build --no-cache . --file Dockerfile --tag angular-v14-nes --build-arg NES_AUTH_TOKEN=${{ secrets.NES_AUTH_TOKEN }}
    - name: Run Docker container
      run: |
        docker run -d -p 4200:4200 --name angular-v14-nes angular-v14-nes
        sleep 10 # Give some time for the application to start

    - name: Check Docker container logs
      run: |
        docker logs angular-v14-nes

    - name: Check Docker container exit status
      run: |
        sleep 10 # Additional wait time if needed
        CONTAINER_EXIT_CODE=$(docker inspect angular-v14-nes --format='{{.State.ExitCode}}')
        if [ "$CONTAINER_EXIT_CODE" != "0" ]; then
          echo "Container exited with code $CONTAINER_EXIT_CODE"
          exit 1
        fi
